from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.waardetabel import Waardetabel
from openapi_server import util

from openapi_server.models.waardetabel import Waardetabel  # noqa: E501

class AbstractNationaliteit(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, reden_opname=None):  # noqa: E501
        """AbstractNationaliteit - a model defined in OpenAPI

        :param type: The type of this AbstractNationaliteit.  # noqa: E501
        :type type: str
        :param reden_opname: The reden_opname of this AbstractNationaliteit.  # noqa: E501
        :type reden_opname: Waardetabel
        """
        self.openapi_types = {
            'type': str,
            'reden_opname': Waardetabel
        }

        self.attribute_map = {
            'type': 'type',
            'reden_opname': 'redenOpname'
        }

        self._type = type
        self._reden_opname = reden_opname

    @classmethod
    def from_dict(cls, dikt) -> 'AbstractNationaliteit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AbstractNationaliteit of this AbstractNationaliteit.  # noqa: E501
        :rtype: AbstractNationaliteit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this AbstractNationaliteit.


        :return: The type of this AbstractNationaliteit.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AbstractNationaliteit.


        :param type: The type of this AbstractNationaliteit.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def reden_opname(self) -> Waardetabel:
        """Gets the reden_opname of this AbstractNationaliteit.


        :return: The reden_opname of this AbstractNationaliteit.
        :rtype: Waardetabel
        """
        return self._reden_opname

    @reden_opname.setter
    def reden_opname(self, reden_opname: Waardetabel):
        """Sets the reden_opname of this AbstractNationaliteit.


        :param reden_opname: The reden_opname of this AbstractNationaliteit.
        :type reden_opname: Waardetabel
        """

        self._reden_opname = reden_opname
