from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server.models.waardetabel import Waardetabel
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501
from openapi_server.models.waardetabel import Waardetabel  # noqa: E501

class EuropeesKiesrecht(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, aanduiding=None, einddatum_uitsluiting=None):  # noqa: E501
        """EuropeesKiesrecht - a model defined in OpenAPI

        :param aanduiding: The aanduiding of this EuropeesKiesrecht.  # noqa: E501
        :type aanduiding: Waardetabel
        :param einddatum_uitsluiting: The einddatum_uitsluiting of this EuropeesKiesrecht.  # noqa: E501
        :type einddatum_uitsluiting: AbstractDatum
        """
        self.openapi_types = {
            'aanduiding': Waardetabel,
            'einddatum_uitsluiting': AbstractDatum
        }

        self.attribute_map = {
            'aanduiding': 'aanduiding',
            'einddatum_uitsluiting': 'einddatumUitsluiting'
        }

        self._aanduiding = aanduiding
        self._einddatum_uitsluiting = einddatum_uitsluiting

    @classmethod
    def from_dict(cls, dikt) -> 'EuropeesKiesrecht':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EuropeesKiesrecht of this EuropeesKiesrecht.  # noqa: E501
        :rtype: EuropeesKiesrecht
        """
        return util.deserialize_model(dikt, cls)

    @property
    def aanduiding(self) -> Waardetabel:
        """Gets the aanduiding of this EuropeesKiesrecht.


        :return: The aanduiding of this EuropeesKiesrecht.
        :rtype: Waardetabel
        """
        return self._aanduiding

    @aanduiding.setter
    def aanduiding(self, aanduiding: Waardetabel):
        """Sets the aanduiding of this EuropeesKiesrecht.


        :param aanduiding: The aanduiding of this EuropeesKiesrecht.
        :type aanduiding: Waardetabel
        """

        self._aanduiding = aanduiding

    @property
    def einddatum_uitsluiting(self) -> AbstractDatum:
        """Gets the einddatum_uitsluiting of this EuropeesKiesrecht.


        :return: The einddatum_uitsluiting of this EuropeesKiesrecht.
        :rtype: AbstractDatum
        """
        return self._einddatum_uitsluiting

    @einddatum_uitsluiting.setter
    def einddatum_uitsluiting(self, einddatum_uitsluiting: AbstractDatum):
        """Sets the einddatum_uitsluiting of this EuropeesKiesrecht.


        :param einddatum_uitsluiting: The einddatum_uitsluiting of this EuropeesKiesrecht.
        :type einddatum_uitsluiting: AbstractDatum
        """

        self._einddatum_uitsluiting = einddatum_uitsluiting
