from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class GeboorteBasis(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum=None):  # noqa: E501
        """GeboorteBasis - a model defined in OpenAPI

        :param datum: The datum of this GeboorteBasis.  # noqa: E501
        :type datum: AbstractDatum
        """
        self.openapi_types = {
            'datum': AbstractDatum
        }

        self.attribute_map = {
            'datum': 'datum'
        }

        self._datum = datum

    @classmethod
    def from_dict(cls, dikt) -> 'GeboorteBasis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeboorteBasis of this GeboorteBasis.  # noqa: E501
        :rtype: GeboorteBasis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum(self) -> AbstractDatum:
        """Gets the datum of this GeboorteBasis.


        :return: The datum of this GeboorteBasis.
        :rtype: AbstractDatum
        """
        return self._datum

    @datum.setter
    def datum(self, datum: AbstractDatum):
        """Sets the datum of this GeboorteBasis.


        :param datum: The datum of this GeboorteBasis.
        :type datum: AbstractDatum
        """

        self._datum = datum
