from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server.models.geboorte_in_onderzoek_beperkt import GeboorteInOnderzoekBeperkt
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501
from openapi_server.models.geboorte_in_onderzoek_beperkt import GeboorteInOnderzoekBeperkt  # noqa: E501

class GeboorteBeperkt(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum=None, in_onderzoek=None):  # noqa: E501
        """GeboorteBeperkt - a model defined in OpenAPI

        :param datum: The datum of this GeboorteBeperkt.  # noqa: E501
        :type datum: AbstractDatum
        :param in_onderzoek: The in_onderzoek of this GeboorteBeperkt.  # noqa: E501
        :type in_onderzoek: GeboorteInOnderzoekBeperkt
        """
        self.openapi_types = {
            'datum': AbstractDatum,
            'in_onderzoek': GeboorteInOnderzoekBeperkt
        }

        self.attribute_map = {
            'datum': 'datum',
            'in_onderzoek': 'inOnderzoek'
        }

        self._datum = datum
        self._in_onderzoek = in_onderzoek

    @classmethod
    def from_dict(cls, dikt) -> 'GeboorteBeperkt':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeboorteBeperkt of this GeboorteBeperkt.  # noqa: E501
        :rtype: GeboorteBeperkt
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum(self) -> AbstractDatum:
        """Gets the datum of this GeboorteBeperkt.


        :return: The datum of this GeboorteBeperkt.
        :rtype: AbstractDatum
        """
        return self._datum

    @datum.setter
    def datum(self, datum: AbstractDatum):
        """Sets the datum of this GeboorteBeperkt.


        :param datum: The datum of this GeboorteBeperkt.
        :type datum: AbstractDatum
        """

        self._datum = datum

    @property
    def in_onderzoek(self) -> GeboorteInOnderzoekBeperkt:
        """Gets the in_onderzoek of this GeboorteBeperkt.


        :return: The in_onderzoek of this GeboorteBeperkt.
        :rtype: GeboorteInOnderzoekBeperkt
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: GeboorteInOnderzoekBeperkt):
        """Sets the in_onderzoek of this GeboorteBeperkt.


        :param in_onderzoek: The in_onderzoek of this GeboorteBeperkt.
        :type in_onderzoek: GeboorteInOnderzoekBeperkt
        """

        self._in_onderzoek = in_onderzoek
