from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class ImmigratieInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, datum_vestiging_in_nederland=None, land_vanwaar_ingeschreven=None, vanuit_verblijfplaats_onbekend=None, indicatie_vestiging_vanuit_buitenland=None):  # noqa: E501
        """ImmigratieInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this ImmigratieInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param datum_vestiging_in_nederland: The datum_vestiging_in_nederland of this ImmigratieInOnderzoek.  # noqa: E501
        :type datum_vestiging_in_nederland: bool
        :param land_vanwaar_ingeschreven: The land_vanwaar_ingeschreven of this ImmigratieInOnderzoek.  # noqa: E501
        :type land_vanwaar_ingeschreven: bool
        :param vanuit_verblijfplaats_onbekend: The vanuit_verblijfplaats_onbekend of this ImmigratieInOnderzoek.  # noqa: E501
        :type vanuit_verblijfplaats_onbekend: bool
        :param indicatie_vestiging_vanuit_buitenland: The indicatie_vestiging_vanuit_buitenland of this ImmigratieInOnderzoek.  # noqa: E501
        :type indicatie_vestiging_vanuit_buitenland: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'datum_vestiging_in_nederland': bool,
            'land_vanwaar_ingeschreven': bool,
            'vanuit_verblijfplaats_onbekend': bool,
            'indicatie_vestiging_vanuit_buitenland': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'datum_vestiging_in_nederland': 'datumVestigingInNederland',
            'land_vanwaar_ingeschreven': 'landVanwaarIngeschreven',
            'vanuit_verblijfplaats_onbekend': 'vanuitVerblijfplaatsOnbekend',
            'indicatie_vestiging_vanuit_buitenland': 'indicatieVestigingVanuitBuitenland'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._datum_vestiging_in_nederland = datum_vestiging_in_nederland
        self._land_vanwaar_ingeschreven = land_vanwaar_ingeschreven
        self._vanuit_verblijfplaats_onbekend = vanuit_verblijfplaats_onbekend
        self._indicatie_vestiging_vanuit_buitenland = indicatie_vestiging_vanuit_buitenland

    @classmethod
    def from_dict(cls, dikt) -> 'ImmigratieInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImmigratieInOnderzoek of this ImmigratieInOnderzoek.  # noqa: E501
        :rtype: ImmigratieInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this ImmigratieInOnderzoek.


        :return: The datum_ingang_onderzoek of this ImmigratieInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this ImmigratieInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this ImmigratieInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def datum_vestiging_in_nederland(self) -> bool:
        """Gets the datum_vestiging_in_nederland of this ImmigratieInOnderzoek.


        :return: The datum_vestiging_in_nederland of this ImmigratieInOnderzoek.
        :rtype: bool
        """
        return self._datum_vestiging_in_nederland

    @datum_vestiging_in_nederland.setter
    def datum_vestiging_in_nederland(self, datum_vestiging_in_nederland: bool):
        """Sets the datum_vestiging_in_nederland of this ImmigratieInOnderzoek.


        :param datum_vestiging_in_nederland: The datum_vestiging_in_nederland of this ImmigratieInOnderzoek.
        :type datum_vestiging_in_nederland: bool
        """

        self._datum_vestiging_in_nederland = datum_vestiging_in_nederland

    @property
    def land_vanwaar_ingeschreven(self) -> bool:
        """Gets the land_vanwaar_ingeschreven of this ImmigratieInOnderzoek.


        :return: The land_vanwaar_ingeschreven of this ImmigratieInOnderzoek.
        :rtype: bool
        """
        return self._land_vanwaar_ingeschreven

    @land_vanwaar_ingeschreven.setter
    def land_vanwaar_ingeschreven(self, land_vanwaar_ingeschreven: bool):
        """Sets the land_vanwaar_ingeschreven of this ImmigratieInOnderzoek.


        :param land_vanwaar_ingeschreven: The land_vanwaar_ingeschreven of this ImmigratieInOnderzoek.
        :type land_vanwaar_ingeschreven: bool
        """

        self._land_vanwaar_ingeschreven = land_vanwaar_ingeschreven

    @property
    def vanuit_verblijfplaats_onbekend(self) -> bool:
        """Gets the vanuit_verblijfplaats_onbekend of this ImmigratieInOnderzoek.


        :return: The vanuit_verblijfplaats_onbekend of this ImmigratieInOnderzoek.
        :rtype: bool
        """
        return self._vanuit_verblijfplaats_onbekend

    @vanuit_verblijfplaats_onbekend.setter
    def vanuit_verblijfplaats_onbekend(self, vanuit_verblijfplaats_onbekend: bool):
        """Sets the vanuit_verblijfplaats_onbekend of this ImmigratieInOnderzoek.


        :param vanuit_verblijfplaats_onbekend: The vanuit_verblijfplaats_onbekend of this ImmigratieInOnderzoek.
        :type vanuit_verblijfplaats_onbekend: bool
        """

        self._vanuit_verblijfplaats_onbekend = vanuit_verblijfplaats_onbekend

    @property
    def indicatie_vestiging_vanuit_buitenland(self) -> bool:
        """Gets the indicatie_vestiging_vanuit_buitenland of this ImmigratieInOnderzoek.


        :return: The indicatie_vestiging_vanuit_buitenland of this ImmigratieInOnderzoek.
        :rtype: bool
        """
        return self._indicatie_vestiging_vanuit_buitenland

    @indicatie_vestiging_vanuit_buitenland.setter
    def indicatie_vestiging_vanuit_buitenland(self, indicatie_vestiging_vanuit_buitenland: bool):
        """Sets the indicatie_vestiging_vanuit_buitenland of this ImmigratieInOnderzoek.


        :param indicatie_vestiging_vanuit_buitenland: The indicatie_vestiging_vanuit_buitenland of this ImmigratieInOnderzoek.
        :type indicatie_vestiging_vanuit_buitenland: bool
        """

        self._indicatie_vestiging_vanuit_buitenland = indicatie_vestiging_vanuit_buitenland
