from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class InOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None):  # noqa: E501
        """InOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this InOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @classmethod
    def from_dict(cls, dikt) -> 'InOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InOnderzoek of this InOnderzoek.  # noqa: E501
        :rtype: InOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this InOnderzoek.


        :return: The datum_ingang_onderzoek of this InOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this InOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this InOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
