from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class KindInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, burgerservicenummer=None):  # noqa: E501
        """KindInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this KindInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param burgerservicenummer: The burgerservicenummer of this KindInOnderzoek.  # noqa: E501
        :type burgerservicenummer: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'burgerservicenummer': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'burgerservicenummer': 'burgerservicenummer'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._burgerservicenummer = burgerservicenummer

    @classmethod
    def from_dict(cls, dikt) -> 'KindInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The KindInOnderzoek of this KindInOnderzoek.  # noqa: E501
        :rtype: KindInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this KindInOnderzoek.


        :return: The datum_ingang_onderzoek of this KindInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this KindInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this KindInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def burgerservicenummer(self) -> bool:
        """Gets the burgerservicenummer of this KindInOnderzoek.


        :return: The burgerservicenummer of this KindInOnderzoek.
        :rtype: bool
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: bool):
        """Sets the burgerservicenummer of this KindInOnderzoek.


        :param burgerservicenummer: The burgerservicenummer of this KindInOnderzoek.
        :type burgerservicenummer: bool
        """

        self._burgerservicenummer = burgerservicenummer
