from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server.models.abstract_verblijfplaats import AbstractVerblijfplaats
from openapi_server.models.locatie_all_of_datum_ingang_geldigheid import LocatieAllOfDatumIngangGeldigheid
from openapi_server.models.locatie_in_onderzoek import LocatieInOnderzoek
from openapi_server.models.verblijfadres_locatie import VerblijfadresLocatie
from openapi_server.models.waardetabel import Waardetabel
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501
from openapi_server.models.abstract_verblijfplaats import AbstractVerblijfplaats  # noqa: E501
from openapi_server.models.locatie_all_of_datum_ingang_geldigheid import LocatieAllOfDatumIngangGeldigheid  # noqa: E501
from openapi_server.models.locatie_in_onderzoek import LocatieInOnderzoek  # noqa: E501
from openapi_server.models.verblijfadres_locatie import VerblijfadresLocatie  # noqa: E501
from openapi_server.models.waardetabel import Waardetabel  # noqa: E501

class Locatie(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, datum_van=None, functie_adres=None, verblijfadres=None, datum_ingang_geldigheid=None, indicatie_vastgesteld_verblijft_niet_op_adres=None, in_onderzoek=None):  # noqa: E501
        """Locatie - a model defined in OpenAPI

        :param type: The type of this Locatie.  # noqa: E501
        :type type: str
        :param datum_van: The datum_van of this Locatie.  # noqa: E501
        :type datum_van: AbstractDatum
        :param functie_adres: The functie_adres of this Locatie.  # noqa: E501
        :type functie_adres: Waardetabel
        :param verblijfadres: The verblijfadres of this Locatie.  # noqa: E501
        :type verblijfadres: VerblijfadresLocatie
        :param datum_ingang_geldigheid: The datum_ingang_geldigheid of this Locatie.  # noqa: E501
        :type datum_ingang_geldigheid: LocatieAllOfDatumIngangGeldigheid
        :param indicatie_vastgesteld_verblijft_niet_op_adres: The indicatie_vastgesteld_verblijft_niet_op_adres of this Locatie.  # noqa: E501
        :type indicatie_vastgesteld_verblijft_niet_op_adres: bool
        :param in_onderzoek: The in_onderzoek of this Locatie.  # noqa: E501
        :type in_onderzoek: LocatieInOnderzoek
        """
        self.openapi_types = {
            'type': str,
            'datum_van': AbstractDatum,
            'functie_adres': Waardetabel,
            'verblijfadres': VerblijfadresLocatie,
            'datum_ingang_geldigheid': LocatieAllOfDatumIngangGeldigheid,
            'indicatie_vastgesteld_verblijft_niet_op_adres': bool,
            'in_onderzoek': LocatieInOnderzoek
        }

        self.attribute_map = {
            'type': 'type',
            'datum_van': 'datumVan',
            'functie_adres': 'functieAdres',
            'verblijfadres': 'verblijfadres',
            'datum_ingang_geldigheid': 'datumIngangGeldigheid',
            'indicatie_vastgesteld_verblijft_niet_op_adres': 'indicatieVastgesteldVerblijftNietOpAdres',
            'in_onderzoek': 'inOnderzoek'
        }

        self._type = type
        self._datum_van = datum_van
        self._functie_adres = functie_adres
        self._verblijfadres = verblijfadres
        self._datum_ingang_geldigheid = datum_ingang_geldigheid
        self._indicatie_vastgesteld_verblijft_niet_op_adres = indicatie_vastgesteld_verblijft_niet_op_adres
        self._in_onderzoek = in_onderzoek

    @classmethod
    def from_dict(cls, dikt) -> 'Locatie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Locatie of this Locatie.  # noqa: E501
        :rtype: Locatie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Locatie.


        :return: The type of this Locatie.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Locatie.


        :param type: The type of this Locatie.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def datum_van(self) -> AbstractDatum:
        """Gets the datum_van of this Locatie.


        :return: The datum_van of this Locatie.
        :rtype: AbstractDatum
        """
        return self._datum_van

    @datum_van.setter
    def datum_van(self, datum_van: AbstractDatum):
        """Sets the datum_van of this Locatie.


        :param datum_van: The datum_van of this Locatie.
        :type datum_van: AbstractDatum
        """

        self._datum_van = datum_van

    @property
    def functie_adres(self) -> Waardetabel:
        """Gets the functie_adres of this Locatie.


        :return: The functie_adres of this Locatie.
        :rtype: Waardetabel
        """
        return self._functie_adres

    @functie_adres.setter
    def functie_adres(self, functie_adres: Waardetabel):
        """Sets the functie_adres of this Locatie.


        :param functie_adres: The functie_adres of this Locatie.
        :type functie_adres: Waardetabel
        """

        self._functie_adres = functie_adres

    @property
    def verblijfadres(self) -> VerblijfadresLocatie:
        """Gets the verblijfadres of this Locatie.


        :return: The verblijfadres of this Locatie.
        :rtype: VerblijfadresLocatie
        """
        return self._verblijfadres

    @verblijfadres.setter
    def verblijfadres(self, verblijfadres: VerblijfadresLocatie):
        """Sets the verblijfadres of this Locatie.


        :param verblijfadres: The verblijfadres of this Locatie.
        :type verblijfadres: VerblijfadresLocatie
        """

        self._verblijfadres = verblijfadres

    @property
    def datum_ingang_geldigheid(self) -> LocatieAllOfDatumIngangGeldigheid:
        """Gets the datum_ingang_geldigheid of this Locatie.


        :return: The datum_ingang_geldigheid of this Locatie.
        :rtype: LocatieAllOfDatumIngangGeldigheid
        """
        return self._datum_ingang_geldigheid

    @datum_ingang_geldigheid.setter
    def datum_ingang_geldigheid(self, datum_ingang_geldigheid: LocatieAllOfDatumIngangGeldigheid):
        """Sets the datum_ingang_geldigheid of this Locatie.


        :param datum_ingang_geldigheid: The datum_ingang_geldigheid of this Locatie.
        :type datum_ingang_geldigheid: LocatieAllOfDatumIngangGeldigheid
        """

        self._datum_ingang_geldigheid = datum_ingang_geldigheid

    @property
    def indicatie_vastgesteld_verblijft_niet_op_adres(self) -> bool:
        """Gets the indicatie_vastgesteld_verblijft_niet_op_adres of this Locatie.

        Geeft aan dat is vastgesteld dat de persoon niet meer op de geregistreerde adres/locatie staat ingeschreven.   # noqa: E501

        :return: The indicatie_vastgesteld_verblijft_niet_op_adres of this Locatie.
        :rtype: bool
        """
        return self._indicatie_vastgesteld_verblijft_niet_op_adres

    @indicatie_vastgesteld_verblijft_niet_op_adres.setter
    def indicatie_vastgesteld_verblijft_niet_op_adres(self, indicatie_vastgesteld_verblijft_niet_op_adres: bool):
        """Sets the indicatie_vastgesteld_verblijft_niet_op_adres of this Locatie.

        Geeft aan dat is vastgesteld dat de persoon niet meer op de geregistreerde adres/locatie staat ingeschreven.   # noqa: E501

        :param indicatie_vastgesteld_verblijft_niet_op_adres: The indicatie_vastgesteld_verblijft_niet_op_adres of this Locatie.
        :type indicatie_vastgesteld_verblijft_niet_op_adres: bool
        """

        self._indicatie_vastgesteld_verblijft_niet_op_adres = indicatie_vastgesteld_verblijft_niet_op_adres

    @property
    def in_onderzoek(self) -> LocatieInOnderzoek:
        """Gets the in_onderzoek of this Locatie.


        :return: The in_onderzoek of this Locatie.
        :rtype: LocatieInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: LocatieInOnderzoek):
        """Sets the in_onderzoek of this Locatie.


        :param in_onderzoek: The in_onderzoek of this Locatie.
        :type in_onderzoek: LocatieInOnderzoek
        """

        self._in_onderzoek = in_onderzoek
