from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class Minderjarige(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, burgerservicenummer=None):  # noqa: E501
        """Minderjarige - a model defined in OpenAPI

        :param burgerservicenummer: The burgerservicenummer of this Minderjarige.  # noqa: E501
        :type burgerservicenummer: str
        """
        self.openapi_types = {
            'burgerservicenummer': str
        }

        self.attribute_map = {
            'burgerservicenummer': 'burgerservicenummer'
        }

        self._burgerservicenummer = burgerservicenummer

    @classmethod
    def from_dict(cls, dikt) -> 'Minderjarige':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Minderjarige of this Minderjarige.  # noqa: E501
        :rtype: Minderjarige
        """
        return util.deserialize_model(dikt, cls)

    @property
    def burgerservicenummer(self) -> str:
        """Gets the burgerservicenummer of this Minderjarige.


        :return: The burgerservicenummer of this Minderjarige.
        :rtype: str
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: str):
        """Sets the burgerservicenummer of this Minderjarige.


        :param burgerservicenummer: The burgerservicenummer of this Minderjarige.
        :type burgerservicenummer: str
        """
        if burgerservicenummer is None:
            raise ValueError("Invalid value for `burgerservicenummer`, must not be `None`")  # noqa: E501
        if burgerservicenummer is not None and not re.search(r'^[0-9]{9}$', burgerservicenummer):  # noqa: E501
            raise ValueError(r"Invalid value for `burgerservicenummer`, must be a follow pattern or equal to `/^[0-9]{9}$/`")  # noqa: E501

        self._burgerservicenummer = burgerservicenummer
