from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class NaamInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, voornamen=None, adellijke_titel_predicaat=None, voorvoegsel=None, geslachtsnaam=None, voorletters=None):  # noqa: E501
        """NaamInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this NaamInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param voornamen: The voornamen of this NaamInOnderzoek.  # noqa: E501
        :type voornamen: bool
        :param adellijke_titel_predicaat: The adellijke_titel_predicaat of this NaamInOnderzoek.  # noqa: E501
        :type adellijke_titel_predicaat: bool
        :param voorvoegsel: The voorvoegsel of this NaamInOnderzoek.  # noqa: E501
        :type voorvoegsel: bool
        :param geslachtsnaam: The geslachtsnaam of this NaamInOnderzoek.  # noqa: E501
        :type geslachtsnaam: bool
        :param voorletters: The voorletters of this NaamInOnderzoek.  # noqa: E501
        :type voorletters: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'voornamen': bool,
            'adellijke_titel_predicaat': bool,
            'voorvoegsel': bool,
            'geslachtsnaam': bool,
            'voorletters': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'voornamen': 'voornamen',
            'adellijke_titel_predicaat': 'adellijkeTitelPredicaat',
            'voorvoegsel': 'voorvoegsel',
            'geslachtsnaam': 'geslachtsnaam',
            'voorletters': 'voorletters'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._voornamen = voornamen
        self._adellijke_titel_predicaat = adellijke_titel_predicaat
        self._voorvoegsel = voorvoegsel
        self._geslachtsnaam = geslachtsnaam
        self._voorletters = voorletters

    @classmethod
    def from_dict(cls, dikt) -> 'NaamInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NaamInOnderzoek of this NaamInOnderzoek.  # noqa: E501
        :rtype: NaamInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this NaamInOnderzoek.


        :return: The datum_ingang_onderzoek of this NaamInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this NaamInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this NaamInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def voornamen(self) -> bool:
        """Gets the voornamen of this NaamInOnderzoek.


        :return: The voornamen of this NaamInOnderzoek.
        :rtype: bool
        """
        return self._voornamen

    @voornamen.setter
    def voornamen(self, voornamen: bool):
        """Sets the voornamen of this NaamInOnderzoek.


        :param voornamen: The voornamen of this NaamInOnderzoek.
        :type voornamen: bool
        """

        self._voornamen = voornamen

    @property
    def adellijke_titel_predicaat(self) -> bool:
        """Gets the adellijke_titel_predicaat of this NaamInOnderzoek.


        :return: The adellijke_titel_predicaat of this NaamInOnderzoek.
        :rtype: bool
        """
        return self._adellijke_titel_predicaat

    @adellijke_titel_predicaat.setter
    def adellijke_titel_predicaat(self, adellijke_titel_predicaat: bool):
        """Sets the adellijke_titel_predicaat of this NaamInOnderzoek.


        :param adellijke_titel_predicaat: The adellijke_titel_predicaat of this NaamInOnderzoek.
        :type adellijke_titel_predicaat: bool
        """

        self._adellijke_titel_predicaat = adellijke_titel_predicaat

    @property
    def voorvoegsel(self) -> bool:
        """Gets the voorvoegsel of this NaamInOnderzoek.


        :return: The voorvoegsel of this NaamInOnderzoek.
        :rtype: bool
        """
        return self._voorvoegsel

    @voorvoegsel.setter
    def voorvoegsel(self, voorvoegsel: bool):
        """Sets the voorvoegsel of this NaamInOnderzoek.


        :param voorvoegsel: The voorvoegsel of this NaamInOnderzoek.
        :type voorvoegsel: bool
        """

        self._voorvoegsel = voorvoegsel

    @property
    def geslachtsnaam(self) -> bool:
        """Gets the geslachtsnaam of this NaamInOnderzoek.


        :return: The geslachtsnaam of this NaamInOnderzoek.
        :rtype: bool
        """
        return self._geslachtsnaam

    @geslachtsnaam.setter
    def geslachtsnaam(self, geslachtsnaam: bool):
        """Sets the geslachtsnaam of this NaamInOnderzoek.


        :param geslachtsnaam: The geslachtsnaam of this NaamInOnderzoek.
        :type geslachtsnaam: bool
        """

        self._geslachtsnaam = geslachtsnaam

    @property
    def voorletters(self) -> bool:
        """Gets the voorletters of this NaamInOnderzoek.


        :return: The voorletters of this NaamInOnderzoek.
        :rtype: bool
        """
        return self._voorletters

    @voorletters.setter
    def voorletters(self, voorletters: bool):
        """Sets the voorletters of this NaamInOnderzoek.


        :param voorletters: The voorletters of this NaamInOnderzoek.
        :type voorletters: bool
        """

        self._voorletters = voorletters
