from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class OuderInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, burgerservicenummer=None, datum_ingang_familierechtelijke_betrekking=None, geslacht=None):  # noqa: E501
        """OuderInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this OuderInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param burgerservicenummer: The burgerservicenummer of this OuderInOnderzoek.  # noqa: E501
        :type burgerservicenummer: bool
        :param datum_ingang_familierechtelijke_betrekking: The datum_ingang_familierechtelijke_betrekking of this OuderInOnderzoek.  # noqa: E501
        :type datum_ingang_familierechtelijke_betrekking: bool
        :param geslacht: The geslacht of this OuderInOnderzoek.  # noqa: E501
        :type geslacht: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'burgerservicenummer': bool,
            'datum_ingang_familierechtelijke_betrekking': bool,
            'geslacht': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'burgerservicenummer': 'burgerservicenummer',
            'datum_ingang_familierechtelijke_betrekking': 'datumIngangFamilierechtelijkeBetrekking',
            'geslacht': 'geslacht'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._burgerservicenummer = burgerservicenummer
        self._datum_ingang_familierechtelijke_betrekking = datum_ingang_familierechtelijke_betrekking
        self._geslacht = geslacht

    @classmethod
    def from_dict(cls, dikt) -> 'OuderInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OuderInOnderzoek of this OuderInOnderzoek.  # noqa: E501
        :rtype: OuderInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this OuderInOnderzoek.


        :return: The datum_ingang_onderzoek of this OuderInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this OuderInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this OuderInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def burgerservicenummer(self) -> bool:
        """Gets the burgerservicenummer of this OuderInOnderzoek.


        :return: The burgerservicenummer of this OuderInOnderzoek.
        :rtype: bool
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: bool):
        """Sets the burgerservicenummer of this OuderInOnderzoek.


        :param burgerservicenummer: The burgerservicenummer of this OuderInOnderzoek.
        :type burgerservicenummer: bool
        """

        self._burgerservicenummer = burgerservicenummer

    @property
    def datum_ingang_familierechtelijke_betrekking(self) -> bool:
        """Gets the datum_ingang_familierechtelijke_betrekking of this OuderInOnderzoek.


        :return: The datum_ingang_familierechtelijke_betrekking of this OuderInOnderzoek.
        :rtype: bool
        """
        return self._datum_ingang_familierechtelijke_betrekking

    @datum_ingang_familierechtelijke_betrekking.setter
    def datum_ingang_familierechtelijke_betrekking(self, datum_ingang_familierechtelijke_betrekking: bool):
        """Sets the datum_ingang_familierechtelijke_betrekking of this OuderInOnderzoek.


        :param datum_ingang_familierechtelijke_betrekking: The datum_ingang_familierechtelijke_betrekking of this OuderInOnderzoek.
        :type datum_ingang_familierechtelijke_betrekking: bool
        """

        self._datum_ingang_familierechtelijke_betrekking = datum_ingang_familierechtelijke_betrekking

    @property
    def geslacht(self) -> bool:
        """Gets the geslacht of this OuderInOnderzoek.


        :return: The geslacht of this OuderInOnderzoek.
        :rtype: bool
        """
        return self._geslacht

    @geslacht.setter
    def geslacht(self, geslacht: bool):
        """Sets the geslacht of this OuderInOnderzoek.


        :param geslacht: The geslacht of this OuderInOnderzoek.
        :type geslacht: bool
        """

        self._geslacht = geslacht
