from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server.models.overlijden_in_onderzoek import OverlijdenInOnderzoek
from openapi_server.models.waardetabel import Waardetabel
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501
from openapi_server.models.overlijden_in_onderzoek import OverlijdenInOnderzoek  # noqa: E501
from openapi_server.models.waardetabel import Waardetabel  # noqa: E501

class Overlijden(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum=None, land=None, plaats=None, in_onderzoek=None):  # noqa: E501
        """Overlijden - a model defined in OpenAPI

        :param datum: The datum of this Overlijden.  # noqa: E501
        :type datum: AbstractDatum
        :param land: The land of this Overlijden.  # noqa: E501
        :type land: Waardetabel
        :param plaats: The plaats of this Overlijden.  # noqa: E501
        :type plaats: Waardetabel
        :param in_onderzoek: The in_onderzoek of this Overlijden.  # noqa: E501
        :type in_onderzoek: OverlijdenInOnderzoek
        """
        self.openapi_types = {
            'datum': AbstractDatum,
            'land': Waardetabel,
            'plaats': Waardetabel,
            'in_onderzoek': OverlijdenInOnderzoek
        }

        self.attribute_map = {
            'datum': 'datum',
            'land': 'land',
            'plaats': 'plaats',
            'in_onderzoek': 'inOnderzoek'
        }

        self._datum = datum
        self._land = land
        self._plaats = plaats
        self._in_onderzoek = in_onderzoek

    @classmethod
    def from_dict(cls, dikt) -> 'Overlijden':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Overlijden of this Overlijden.  # noqa: E501
        :rtype: Overlijden
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum(self) -> AbstractDatum:
        """Gets the datum of this Overlijden.


        :return: The datum of this Overlijden.
        :rtype: AbstractDatum
        """
        return self._datum

    @datum.setter
    def datum(self, datum: AbstractDatum):
        """Sets the datum of this Overlijden.


        :param datum: The datum of this Overlijden.
        :type datum: AbstractDatum
        """

        self._datum = datum

    @property
    def land(self) -> Waardetabel:
        """Gets the land of this Overlijden.


        :return: The land of this Overlijden.
        :rtype: Waardetabel
        """
        return self._land

    @land.setter
    def land(self, land: Waardetabel):
        """Sets the land of this Overlijden.


        :param land: The land of this Overlijden.
        :type land: Waardetabel
        """

        self._land = land

    @property
    def plaats(self) -> Waardetabel:
        """Gets the plaats of this Overlijden.


        :return: The plaats of this Overlijden.
        :rtype: Waardetabel
        """
        return self._plaats

    @plaats.setter
    def plaats(self, plaats: Waardetabel):
        """Sets the plaats of this Overlijden.


        :param plaats: The plaats of this Overlijden.
        :type plaats: Waardetabel
        """

        self._plaats = plaats

    @property
    def in_onderzoek(self) -> OverlijdenInOnderzoek:
        """Gets the in_onderzoek of this Overlijden.


        :return: The in_onderzoek of this Overlijden.
        :rtype: OverlijdenInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: OverlijdenInOnderzoek):
        """Sets the in_onderzoek of this Overlijden.


        :param in_onderzoek: The in_onderzoek of this Overlijden.
        :type in_onderzoek: OverlijdenInOnderzoek
        """

        self._in_onderzoek = in_onderzoek
