from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class PartnerInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, burgerservicenummer=None, geslacht=None, soort_verbintenis=None):  # noqa: E501
        """PartnerInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this PartnerInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param burgerservicenummer: The burgerservicenummer of this PartnerInOnderzoek.  # noqa: E501
        :type burgerservicenummer: bool
        :param geslacht: The geslacht of this PartnerInOnderzoek.  # noqa: E501
        :type geslacht: bool
        :param soort_verbintenis: The soort_verbintenis of this PartnerInOnderzoek.  # noqa: E501
        :type soort_verbintenis: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'burgerservicenummer': bool,
            'geslacht': bool,
            'soort_verbintenis': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'burgerservicenummer': 'burgerservicenummer',
            'geslacht': 'geslacht',
            'soort_verbintenis': 'soortVerbintenis'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._burgerservicenummer = burgerservicenummer
        self._geslacht = geslacht
        self._soort_verbintenis = soort_verbintenis

    @classmethod
    def from_dict(cls, dikt) -> 'PartnerInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PartnerInOnderzoek of this PartnerInOnderzoek.  # noqa: E501
        :rtype: PartnerInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this PartnerInOnderzoek.


        :return: The datum_ingang_onderzoek of this PartnerInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this PartnerInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this PartnerInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def burgerservicenummer(self) -> bool:
        """Gets the burgerservicenummer of this PartnerInOnderzoek.


        :return: The burgerservicenummer of this PartnerInOnderzoek.
        :rtype: bool
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: bool):
        """Sets the burgerservicenummer of this PartnerInOnderzoek.


        :param burgerservicenummer: The burgerservicenummer of this PartnerInOnderzoek.
        :type burgerservicenummer: bool
        """

        self._burgerservicenummer = burgerservicenummer

    @property
    def geslacht(self) -> bool:
        """Gets the geslacht of this PartnerInOnderzoek.


        :return: The geslacht of this PartnerInOnderzoek.
        :rtype: bool
        """
        return self._geslacht

    @geslacht.setter
    def geslacht(self, geslacht: bool):
        """Sets the geslacht of this PartnerInOnderzoek.


        :param geslacht: The geslacht of this PartnerInOnderzoek.
        :type geslacht: bool
        """

        self._geslacht = geslacht

    @property
    def soort_verbintenis(self) -> bool:
        """Gets the soort_verbintenis of this PartnerInOnderzoek.


        :return: The soort_verbintenis of this PartnerInOnderzoek.
        :rtype: bool
        """
        return self._soort_verbintenis

    @soort_verbintenis.setter
    def soort_verbintenis(self, soort_verbintenis: bool):
        """Sets the soort_verbintenis of this PartnerInOnderzoek.


        :param soort_verbintenis: The soort_verbintenis of this PartnerInOnderzoek.
        :type soort_verbintenis: bool
        """

        self._soort_verbintenis = soort_verbintenis
