from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class PersoonInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek_persoon=None, datum_ingang_onderzoek_gemeente=None, datum_ingang_onderzoek_gezag=None, burgerservicenummer=None, geslacht=None, leeftijd=None, gemeente_van_inschrijving=None, datum_inschrijving_in_gemeente=None, indicatie_curatele_register=None, indicatie_gezag_minderjarige=None):  # noqa: E501
        """PersoonInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek_persoon: The datum_ingang_onderzoek_persoon of this PersoonInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek_persoon: AbstractDatum
        :param datum_ingang_onderzoek_gemeente: The datum_ingang_onderzoek_gemeente of this PersoonInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek_gemeente: AbstractDatum
        :param datum_ingang_onderzoek_gezag: The datum_ingang_onderzoek_gezag of this PersoonInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek_gezag: AbstractDatum
        :param burgerservicenummer: The burgerservicenummer of this PersoonInOnderzoek.  # noqa: E501
        :type burgerservicenummer: bool
        :param geslacht: The geslacht of this PersoonInOnderzoek.  # noqa: E501
        :type geslacht: bool
        :param leeftijd: The leeftijd of this PersoonInOnderzoek.  # noqa: E501
        :type leeftijd: bool
        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this PersoonInOnderzoek.  # noqa: E501
        :type gemeente_van_inschrijving: bool
        :param datum_inschrijving_in_gemeente: The datum_inschrijving_in_gemeente of this PersoonInOnderzoek.  # noqa: E501
        :type datum_inschrijving_in_gemeente: bool
        :param indicatie_curatele_register: The indicatie_curatele_register of this PersoonInOnderzoek.  # noqa: E501
        :type indicatie_curatele_register: bool
        :param indicatie_gezag_minderjarige: The indicatie_gezag_minderjarige of this PersoonInOnderzoek.  # noqa: E501
        :type indicatie_gezag_minderjarige: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek_persoon': AbstractDatum,
            'datum_ingang_onderzoek_gemeente': AbstractDatum,
            'datum_ingang_onderzoek_gezag': AbstractDatum,
            'burgerservicenummer': bool,
            'geslacht': bool,
            'leeftijd': bool,
            'gemeente_van_inschrijving': bool,
            'datum_inschrijving_in_gemeente': bool,
            'indicatie_curatele_register': bool,
            'indicatie_gezag_minderjarige': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek_persoon': 'datumIngangOnderzoekPersoon',
            'datum_ingang_onderzoek_gemeente': 'datumIngangOnderzoekGemeente',
            'datum_ingang_onderzoek_gezag': 'datumIngangOnderzoekGezag',
            'burgerservicenummer': 'burgerservicenummer',
            'geslacht': 'geslacht',
            'leeftijd': 'leeftijd',
            'gemeente_van_inschrijving': 'gemeenteVanInschrijving',
            'datum_inschrijving_in_gemeente': 'datumInschrijvingInGemeente',
            'indicatie_curatele_register': 'indicatieCurateleRegister',
            'indicatie_gezag_minderjarige': 'indicatieGezagMinderjarige'
        }

        self._datum_ingang_onderzoek_persoon = datum_ingang_onderzoek_persoon
        self._datum_ingang_onderzoek_gemeente = datum_ingang_onderzoek_gemeente
        self._datum_ingang_onderzoek_gezag = datum_ingang_onderzoek_gezag
        self._burgerservicenummer = burgerservicenummer
        self._geslacht = geslacht
        self._leeftijd = leeftijd
        self._gemeente_van_inschrijving = gemeente_van_inschrijving
        self._datum_inschrijving_in_gemeente = datum_inschrijving_in_gemeente
        self._indicatie_curatele_register = indicatie_curatele_register
        self._indicatie_gezag_minderjarige = indicatie_gezag_minderjarige

    @classmethod
    def from_dict(cls, dikt) -> 'PersoonInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PersoonInOnderzoek of this PersoonInOnderzoek.  # noqa: E501
        :rtype: PersoonInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek_persoon(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek_persoon of this PersoonInOnderzoek.


        :return: The datum_ingang_onderzoek_persoon of this PersoonInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek_persoon

    @datum_ingang_onderzoek_persoon.setter
    def datum_ingang_onderzoek_persoon(self, datum_ingang_onderzoek_persoon: AbstractDatum):
        """Sets the datum_ingang_onderzoek_persoon of this PersoonInOnderzoek.


        :param datum_ingang_onderzoek_persoon: The datum_ingang_onderzoek_persoon of this PersoonInOnderzoek.
        :type datum_ingang_onderzoek_persoon: AbstractDatum
        """

        self._datum_ingang_onderzoek_persoon = datum_ingang_onderzoek_persoon

    @property
    def datum_ingang_onderzoek_gemeente(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek_gemeente of this PersoonInOnderzoek.


        :return: The datum_ingang_onderzoek_gemeente of this PersoonInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek_gemeente

    @datum_ingang_onderzoek_gemeente.setter
    def datum_ingang_onderzoek_gemeente(self, datum_ingang_onderzoek_gemeente: AbstractDatum):
        """Sets the datum_ingang_onderzoek_gemeente of this PersoonInOnderzoek.


        :param datum_ingang_onderzoek_gemeente: The datum_ingang_onderzoek_gemeente of this PersoonInOnderzoek.
        :type datum_ingang_onderzoek_gemeente: AbstractDatum
        """

        self._datum_ingang_onderzoek_gemeente = datum_ingang_onderzoek_gemeente

    @property
    def datum_ingang_onderzoek_gezag(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek_gezag of this PersoonInOnderzoek.


        :return: The datum_ingang_onderzoek_gezag of this PersoonInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek_gezag

    @datum_ingang_onderzoek_gezag.setter
    def datum_ingang_onderzoek_gezag(self, datum_ingang_onderzoek_gezag: AbstractDatum):
        """Sets the datum_ingang_onderzoek_gezag of this PersoonInOnderzoek.


        :param datum_ingang_onderzoek_gezag: The datum_ingang_onderzoek_gezag of this PersoonInOnderzoek.
        :type datum_ingang_onderzoek_gezag: AbstractDatum
        """

        self._datum_ingang_onderzoek_gezag = datum_ingang_onderzoek_gezag

    @property
    def burgerservicenummer(self) -> bool:
        """Gets the burgerservicenummer of this PersoonInOnderzoek.


        :return: The burgerservicenummer of this PersoonInOnderzoek.
        :rtype: bool
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: bool):
        """Sets the burgerservicenummer of this PersoonInOnderzoek.


        :param burgerservicenummer: The burgerservicenummer of this PersoonInOnderzoek.
        :type burgerservicenummer: bool
        """

        self._burgerservicenummer = burgerservicenummer

    @property
    def geslacht(self) -> bool:
        """Gets the geslacht of this PersoonInOnderzoek.


        :return: The geslacht of this PersoonInOnderzoek.
        :rtype: bool
        """
        return self._geslacht

    @geslacht.setter
    def geslacht(self, geslacht: bool):
        """Sets the geslacht of this PersoonInOnderzoek.


        :param geslacht: The geslacht of this PersoonInOnderzoek.
        :type geslacht: bool
        """

        self._geslacht = geslacht

    @property
    def leeftijd(self) -> bool:
        """Gets the leeftijd of this PersoonInOnderzoek.


        :return: The leeftijd of this PersoonInOnderzoek.
        :rtype: bool
        """
        return self._leeftijd

    @leeftijd.setter
    def leeftijd(self, leeftijd: bool):
        """Sets the leeftijd of this PersoonInOnderzoek.


        :param leeftijd: The leeftijd of this PersoonInOnderzoek.
        :type leeftijd: bool
        """

        self._leeftijd = leeftijd

    @property
    def gemeente_van_inschrijving(self) -> bool:
        """Gets the gemeente_van_inschrijving of this PersoonInOnderzoek.


        :return: The gemeente_van_inschrijving of this PersoonInOnderzoek.
        :rtype: bool
        """
        return self._gemeente_van_inschrijving

    @gemeente_van_inschrijving.setter
    def gemeente_van_inschrijving(self, gemeente_van_inschrijving: bool):
        """Sets the gemeente_van_inschrijving of this PersoonInOnderzoek.


        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this PersoonInOnderzoek.
        :type gemeente_van_inschrijving: bool
        """

        self._gemeente_van_inschrijving = gemeente_van_inschrijving

    @property
    def datum_inschrijving_in_gemeente(self) -> bool:
        """Gets the datum_inschrijving_in_gemeente of this PersoonInOnderzoek.


        :return: The datum_inschrijving_in_gemeente of this PersoonInOnderzoek.
        :rtype: bool
        """
        return self._datum_inschrijving_in_gemeente

    @datum_inschrijving_in_gemeente.setter
    def datum_inschrijving_in_gemeente(self, datum_inschrijving_in_gemeente: bool):
        """Sets the datum_inschrijving_in_gemeente of this PersoonInOnderzoek.


        :param datum_inschrijving_in_gemeente: The datum_inschrijving_in_gemeente of this PersoonInOnderzoek.
        :type datum_inschrijving_in_gemeente: bool
        """

        self._datum_inschrijving_in_gemeente = datum_inschrijving_in_gemeente

    @property
    def indicatie_curatele_register(self) -> bool:
        """Gets the indicatie_curatele_register of this PersoonInOnderzoek.


        :return: The indicatie_curatele_register of this PersoonInOnderzoek.
        :rtype: bool
        """
        return self._indicatie_curatele_register

    @indicatie_curatele_register.setter
    def indicatie_curatele_register(self, indicatie_curatele_register: bool):
        """Sets the indicatie_curatele_register of this PersoonInOnderzoek.


        :param indicatie_curatele_register: The indicatie_curatele_register of this PersoonInOnderzoek.
        :type indicatie_curatele_register: bool
        """

        self._indicatie_curatele_register = indicatie_curatele_register

    @property
    def indicatie_gezag_minderjarige(self) -> bool:
        """Gets the indicatie_gezag_minderjarige of this PersoonInOnderzoek.


        :return: The indicatie_gezag_minderjarige of this PersoonInOnderzoek.
        :rtype: bool
        """
        return self._indicatie_gezag_minderjarige

    @indicatie_gezag_minderjarige.setter
    def indicatie_gezag_minderjarige(self, indicatie_gezag_minderjarige: bool):
        """Sets the indicatie_gezag_minderjarige of this PersoonInOnderzoek.


        :param indicatie_gezag_minderjarige: The indicatie_gezag_minderjarige of this PersoonInOnderzoek.
        :type indicatie_gezag_minderjarige: bool
        """

        self._indicatie_gezag_minderjarige = indicatie_gezag_minderjarige
