from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class PersoonInOnderzoekBeperkt(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek_persoon=None, burgerservicenummer=None, geslacht=None, leeftijd=None):  # noqa: E501
        """PersoonInOnderzoekBeperkt - a model defined in OpenAPI

        :param datum_ingang_onderzoek_persoon: The datum_ingang_onderzoek_persoon of this PersoonInOnderzoekBeperkt.  # noqa: E501
        :type datum_ingang_onderzoek_persoon: AbstractDatum
        :param burgerservicenummer: The burgerservicenummer of this PersoonInOnderzoekBeperkt.  # noqa: E501
        :type burgerservicenummer: bool
        :param geslacht: The geslacht of this PersoonInOnderzoekBeperkt.  # noqa: E501
        :type geslacht: bool
        :param leeftijd: The leeftijd of this PersoonInOnderzoekBeperkt.  # noqa: E501
        :type leeftijd: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek_persoon': AbstractDatum,
            'burgerservicenummer': bool,
            'geslacht': bool,
            'leeftijd': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek_persoon': 'datumIngangOnderzoekPersoon',
            'burgerservicenummer': 'burgerservicenummer',
            'geslacht': 'geslacht',
            'leeftijd': 'leeftijd'
        }

        self._datum_ingang_onderzoek_persoon = datum_ingang_onderzoek_persoon
        self._burgerservicenummer = burgerservicenummer
        self._geslacht = geslacht
        self._leeftijd = leeftijd

    @classmethod
    def from_dict(cls, dikt) -> 'PersoonInOnderzoekBeperkt':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PersoonInOnderzoekBeperkt of this PersoonInOnderzoekBeperkt.  # noqa: E501
        :rtype: PersoonInOnderzoekBeperkt
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek_persoon(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek_persoon of this PersoonInOnderzoekBeperkt.


        :return: The datum_ingang_onderzoek_persoon of this PersoonInOnderzoekBeperkt.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek_persoon

    @datum_ingang_onderzoek_persoon.setter
    def datum_ingang_onderzoek_persoon(self, datum_ingang_onderzoek_persoon: AbstractDatum):
        """Sets the datum_ingang_onderzoek_persoon of this PersoonInOnderzoekBeperkt.


        :param datum_ingang_onderzoek_persoon: The datum_ingang_onderzoek_persoon of this PersoonInOnderzoekBeperkt.
        :type datum_ingang_onderzoek_persoon: AbstractDatum
        """

        self._datum_ingang_onderzoek_persoon = datum_ingang_onderzoek_persoon

    @property
    def burgerservicenummer(self) -> bool:
        """Gets the burgerservicenummer of this PersoonInOnderzoekBeperkt.


        :return: The burgerservicenummer of this PersoonInOnderzoekBeperkt.
        :rtype: bool
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: bool):
        """Sets the burgerservicenummer of this PersoonInOnderzoekBeperkt.


        :param burgerservicenummer: The burgerservicenummer of this PersoonInOnderzoekBeperkt.
        :type burgerservicenummer: bool
        """

        self._burgerservicenummer = burgerservicenummer

    @property
    def geslacht(self) -> bool:
        """Gets the geslacht of this PersoonInOnderzoekBeperkt.


        :return: The geslacht of this PersoonInOnderzoekBeperkt.
        :rtype: bool
        """
        return self._geslacht

    @geslacht.setter
    def geslacht(self, geslacht: bool):
        """Sets the geslacht of this PersoonInOnderzoekBeperkt.


        :param geslacht: The geslacht of this PersoonInOnderzoekBeperkt.
        :type geslacht: bool
        """

        self._geslacht = geslacht

    @property
    def leeftijd(self) -> bool:
        """Gets the leeftijd of this PersoonInOnderzoekBeperkt.


        :return: The leeftijd of this PersoonInOnderzoekBeperkt.
        :rtype: bool
        """
        return self._leeftijd

    @leeftijd.setter
    def leeftijd(self, leeftijd: bool):
        """Sets the leeftijd of this PersoonInOnderzoekBeperkt.


        :param leeftijd: The leeftijd of this PersoonInOnderzoekBeperkt.
        :type leeftijd: bool
        """

        self._leeftijd = leeftijd
