from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class StaatloosInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, type=None, reden_opname=None):  # noqa: E501
        """StaatloosInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this StaatloosInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param type: The type of this StaatloosInOnderzoek.  # noqa: E501
        :type type: bool
        :param reden_opname: The reden_opname of this StaatloosInOnderzoek.  # noqa: E501
        :type reden_opname: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'type': bool,
            'reden_opname': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'type': 'type',
            'reden_opname': 'redenOpname'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._type = type
        self._reden_opname = reden_opname

    @classmethod
    def from_dict(cls, dikt) -> 'StaatloosInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StaatloosInOnderzoek of this StaatloosInOnderzoek.  # noqa: E501
        :rtype: StaatloosInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this StaatloosInOnderzoek.


        :return: The datum_ingang_onderzoek of this StaatloosInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this StaatloosInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this StaatloosInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def type(self) -> bool:
        """Gets the type of this StaatloosInOnderzoek.


        :return: The type of this StaatloosInOnderzoek.
        :rtype: bool
        """
        return self._type

    @type.setter
    def type(self, type: bool):
        """Sets the type of this StaatloosInOnderzoek.


        :param type: The type of this StaatloosInOnderzoek.
        :type type: bool
        """

        self._type = type

    @property
    def reden_opname(self) -> bool:
        """Gets the reden_opname of this StaatloosInOnderzoek.


        :return: The reden_opname of this StaatloosInOnderzoek.
        :rtype: bool
        """
        return self._reden_opname

    @reden_opname.setter
    def reden_opname(self, reden_opname: bool):
        """Sets the reden_opname of this StaatloosInOnderzoek.


        :param reden_opname: The reden_opname of this StaatloosInOnderzoek.
        :type reden_opname: bool
        """

        self._reden_opname = reden_opname
