from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class UitsluitingKiesrecht(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uitgesloten_van_kiesrecht=None, einddatum=None):  # noqa: E501
        """UitsluitingKiesrecht - a model defined in OpenAPI

        :param uitgesloten_van_kiesrecht: The uitgesloten_van_kiesrecht of this UitsluitingKiesrecht.  # noqa: E501
        :type uitgesloten_van_kiesrecht: bool
        :param einddatum: The einddatum of this UitsluitingKiesrecht.  # noqa: E501
        :type einddatum: AbstractDatum
        """
        self.openapi_types = {
            'uitgesloten_van_kiesrecht': bool,
            'einddatum': AbstractDatum
        }

        self.attribute_map = {
            'uitgesloten_van_kiesrecht': 'uitgeslotenVanKiesrecht',
            'einddatum': 'einddatum'
        }

        self._uitgesloten_van_kiesrecht = uitgesloten_van_kiesrecht
        self._einddatum = einddatum

    @classmethod
    def from_dict(cls, dikt) -> 'UitsluitingKiesrecht':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UitsluitingKiesrecht of this UitsluitingKiesrecht.  # noqa: E501
        :rtype: UitsluitingKiesrecht
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uitgesloten_van_kiesrecht(self) -> bool:
        """Gets the uitgesloten_van_kiesrecht of this UitsluitingKiesrecht.


        :return: The uitgesloten_van_kiesrecht of this UitsluitingKiesrecht.
        :rtype: bool
        """
        return self._uitgesloten_van_kiesrecht

    @uitgesloten_van_kiesrecht.setter
    def uitgesloten_van_kiesrecht(self, uitgesloten_van_kiesrecht: bool):
        """Sets the uitgesloten_van_kiesrecht of this UitsluitingKiesrecht.


        :param uitgesloten_van_kiesrecht: The uitgesloten_van_kiesrecht of this UitsluitingKiesrecht.
        :type uitgesloten_van_kiesrecht: bool
        """

        self._uitgesloten_van_kiesrecht = uitgesloten_van_kiesrecht

    @property
    def einddatum(self) -> AbstractDatum:
        """Gets the einddatum of this UitsluitingKiesrecht.


        :return: The einddatum of this UitsluitingKiesrecht.
        :rtype: AbstractDatum
        """
        return self._einddatum

    @einddatum.setter
    def einddatum(self, einddatum: AbstractDatum):
        """Sets the einddatum of this UitsluitingKiesrecht.


        :param einddatum: The einddatum of this UitsluitingKiesrecht.
        :type einddatum: AbstractDatum
        """

        self._einddatum = einddatum
