from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class VerblijfadresBinnenlandInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, aanduiding_bij_huisnummer=None, huisletter=None, huisnummer=None, huisnummertoevoeging=None, officiele_straatnaam=None, postcode=None, korte_straatnaam=None, woonplaats=None):  # noqa: E501
        """VerblijfadresBinnenlandInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param aanduiding_bij_huisnummer: The aanduiding_bij_huisnummer of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type aanduiding_bij_huisnummer: bool
        :param huisletter: The huisletter of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type huisletter: bool
        :param huisnummer: The huisnummer of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type huisnummer: bool
        :param huisnummertoevoeging: The huisnummertoevoeging of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type huisnummertoevoeging: bool
        :param officiele_straatnaam: The officiele_straatnaam of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type officiele_straatnaam: bool
        :param postcode: The postcode of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type postcode: bool
        :param korte_straatnaam: The korte_straatnaam of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type korte_straatnaam: bool
        :param woonplaats: The woonplaats of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :type woonplaats: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'aanduiding_bij_huisnummer': bool,
            'huisletter': bool,
            'huisnummer': bool,
            'huisnummertoevoeging': bool,
            'officiele_straatnaam': bool,
            'postcode': bool,
            'korte_straatnaam': bool,
            'woonplaats': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'aanduiding_bij_huisnummer': 'aanduidingBijHuisnummer',
            'huisletter': 'huisletter',
            'huisnummer': 'huisnummer',
            'huisnummertoevoeging': 'huisnummertoevoeging',
            'officiele_straatnaam': 'officieleStraatnaam',
            'postcode': 'postcode',
            'korte_straatnaam': 'korteStraatnaam',
            'woonplaats': 'woonplaats'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._aanduiding_bij_huisnummer = aanduiding_bij_huisnummer
        self._huisletter = huisletter
        self._huisnummer = huisnummer
        self._huisnummertoevoeging = huisnummertoevoeging
        self._officiele_straatnaam = officiele_straatnaam
        self._postcode = postcode
        self._korte_straatnaam = korte_straatnaam
        self._woonplaats = woonplaats

    @classmethod
    def from_dict(cls, dikt) -> 'VerblijfadresBinnenlandInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerblijfadresBinnenlandInOnderzoek of this VerblijfadresBinnenlandInOnderzoek.  # noqa: E501
        :rtype: VerblijfadresBinnenlandInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this VerblijfadresBinnenlandInOnderzoek.


        :return: The datum_ingang_onderzoek of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this VerblijfadresBinnenlandInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this VerblijfadresBinnenlandInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def aanduiding_bij_huisnummer(self) -> bool:
        """Gets the aanduiding_bij_huisnummer of this VerblijfadresBinnenlandInOnderzoek.


        :return: The aanduiding_bij_huisnummer of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._aanduiding_bij_huisnummer

    @aanduiding_bij_huisnummer.setter
    def aanduiding_bij_huisnummer(self, aanduiding_bij_huisnummer: bool):
        """Sets the aanduiding_bij_huisnummer of this VerblijfadresBinnenlandInOnderzoek.


        :param aanduiding_bij_huisnummer: The aanduiding_bij_huisnummer of this VerblijfadresBinnenlandInOnderzoek.
        :type aanduiding_bij_huisnummer: bool
        """

        self._aanduiding_bij_huisnummer = aanduiding_bij_huisnummer

    @property
    def huisletter(self) -> bool:
        """Gets the huisletter of this VerblijfadresBinnenlandInOnderzoek.


        :return: The huisletter of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._huisletter

    @huisletter.setter
    def huisletter(self, huisletter: bool):
        """Sets the huisletter of this VerblijfadresBinnenlandInOnderzoek.


        :param huisletter: The huisletter of this VerblijfadresBinnenlandInOnderzoek.
        :type huisletter: bool
        """

        self._huisletter = huisletter

    @property
    def huisnummer(self) -> bool:
        """Gets the huisnummer of this VerblijfadresBinnenlandInOnderzoek.


        :return: The huisnummer of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._huisnummer

    @huisnummer.setter
    def huisnummer(self, huisnummer: bool):
        """Sets the huisnummer of this VerblijfadresBinnenlandInOnderzoek.


        :param huisnummer: The huisnummer of this VerblijfadresBinnenlandInOnderzoek.
        :type huisnummer: bool
        """

        self._huisnummer = huisnummer

    @property
    def huisnummertoevoeging(self) -> bool:
        """Gets the huisnummertoevoeging of this VerblijfadresBinnenlandInOnderzoek.


        :return: The huisnummertoevoeging of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._huisnummertoevoeging

    @huisnummertoevoeging.setter
    def huisnummertoevoeging(self, huisnummertoevoeging: bool):
        """Sets the huisnummertoevoeging of this VerblijfadresBinnenlandInOnderzoek.


        :param huisnummertoevoeging: The huisnummertoevoeging of this VerblijfadresBinnenlandInOnderzoek.
        :type huisnummertoevoeging: bool
        """

        self._huisnummertoevoeging = huisnummertoevoeging

    @property
    def officiele_straatnaam(self) -> bool:
        """Gets the officiele_straatnaam of this VerblijfadresBinnenlandInOnderzoek.


        :return: The officiele_straatnaam of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._officiele_straatnaam

    @officiele_straatnaam.setter
    def officiele_straatnaam(self, officiele_straatnaam: bool):
        """Sets the officiele_straatnaam of this VerblijfadresBinnenlandInOnderzoek.


        :param officiele_straatnaam: The officiele_straatnaam of this VerblijfadresBinnenlandInOnderzoek.
        :type officiele_straatnaam: bool
        """

        self._officiele_straatnaam = officiele_straatnaam

    @property
    def postcode(self) -> bool:
        """Gets the postcode of this VerblijfadresBinnenlandInOnderzoek.


        :return: The postcode of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._postcode

    @postcode.setter
    def postcode(self, postcode: bool):
        """Sets the postcode of this VerblijfadresBinnenlandInOnderzoek.


        :param postcode: The postcode of this VerblijfadresBinnenlandInOnderzoek.
        :type postcode: bool
        """

        self._postcode = postcode

    @property
    def korte_straatnaam(self) -> bool:
        """Gets the korte_straatnaam of this VerblijfadresBinnenlandInOnderzoek.


        :return: The korte_straatnaam of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._korte_straatnaam

    @korte_straatnaam.setter
    def korte_straatnaam(self, korte_straatnaam: bool):
        """Sets the korte_straatnaam of this VerblijfadresBinnenlandInOnderzoek.


        :param korte_straatnaam: The korte_straatnaam of this VerblijfadresBinnenlandInOnderzoek.
        :type korte_straatnaam: bool
        """

        self._korte_straatnaam = korte_straatnaam

    @property
    def woonplaats(self) -> bool:
        """Gets the woonplaats of this VerblijfadresBinnenlandInOnderzoek.


        :return: The woonplaats of this VerblijfadresBinnenlandInOnderzoek.
        :rtype: bool
        """
        return self._woonplaats

    @woonplaats.setter
    def woonplaats(self, woonplaats: bool):
        """Sets the woonplaats of this VerblijfadresBinnenlandInOnderzoek.


        :param woonplaats: The woonplaats of this VerblijfadresBinnenlandInOnderzoek.
        :type woonplaats: bool
        """

        self._woonplaats = woonplaats
