from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server.models.abstract_verblijfplaats import AbstractVerblijfplaats
from openapi_server.models.verblijfadres_buitenland import VerblijfadresBuitenland
from openapi_server.models.verblijfplaats_buitenland_all_of_datum_ingang_geldigheid import VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid
from openapi_server.models.verblijfplaats_buitenland_in_onderzoek import VerblijfplaatsBuitenlandInOnderzoek
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501
from openapi_server.models.abstract_verblijfplaats import AbstractVerblijfplaats  # noqa: E501
from openapi_server.models.verblijfadres_buitenland import VerblijfadresBuitenland  # noqa: E501
from openapi_server.models.verblijfplaats_buitenland_all_of_datum_ingang_geldigheid import VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid  # noqa: E501
from openapi_server.models.verblijfplaats_buitenland_in_onderzoek import VerblijfplaatsBuitenlandInOnderzoek  # noqa: E501

class VerblijfplaatsBuitenland(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, verblijfadres=None, datum_van=None, datum_ingang_geldigheid=None, in_onderzoek=None):  # noqa: E501
        """VerblijfplaatsBuitenland - a model defined in OpenAPI

        :param type: The type of this VerblijfplaatsBuitenland.  # noqa: E501
        :type type: str
        :param verblijfadres: The verblijfadres of this VerblijfplaatsBuitenland.  # noqa: E501
        :type verblijfadres: VerblijfadresBuitenland
        :param datum_van: The datum_van of this VerblijfplaatsBuitenland.  # noqa: E501
        :type datum_van: AbstractDatum
        :param datum_ingang_geldigheid: The datum_ingang_geldigheid of this VerblijfplaatsBuitenland.  # noqa: E501
        :type datum_ingang_geldigheid: VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid
        :param in_onderzoek: The in_onderzoek of this VerblijfplaatsBuitenland.  # noqa: E501
        :type in_onderzoek: VerblijfplaatsBuitenlandInOnderzoek
        """
        self.openapi_types = {
            'type': str,
            'verblijfadres': VerblijfadresBuitenland,
            'datum_van': AbstractDatum,
            'datum_ingang_geldigheid': VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid,
            'in_onderzoek': VerblijfplaatsBuitenlandInOnderzoek
        }

        self.attribute_map = {
            'type': 'type',
            'verblijfadres': 'verblijfadres',
            'datum_van': 'datumVan',
            'datum_ingang_geldigheid': 'datumIngangGeldigheid',
            'in_onderzoek': 'inOnderzoek'
        }

        self._type = type
        self._verblijfadres = verblijfadres
        self._datum_van = datum_van
        self._datum_ingang_geldigheid = datum_ingang_geldigheid
        self._in_onderzoek = in_onderzoek

    @classmethod
    def from_dict(cls, dikt) -> 'VerblijfplaatsBuitenland':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerblijfplaatsBuitenland of this VerblijfplaatsBuitenland.  # noqa: E501
        :rtype: VerblijfplaatsBuitenland
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this VerblijfplaatsBuitenland.


        :return: The type of this VerblijfplaatsBuitenland.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this VerblijfplaatsBuitenland.


        :param type: The type of this VerblijfplaatsBuitenland.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def verblijfadres(self) -> VerblijfadresBuitenland:
        """Gets the verblijfadres of this VerblijfplaatsBuitenland.


        :return: The verblijfadres of this VerblijfplaatsBuitenland.
        :rtype: VerblijfadresBuitenland
        """
        return self._verblijfadres

    @verblijfadres.setter
    def verblijfadres(self, verblijfadres: VerblijfadresBuitenland):
        """Sets the verblijfadres of this VerblijfplaatsBuitenland.


        :param verblijfadres: The verblijfadres of this VerblijfplaatsBuitenland.
        :type verblijfadres: VerblijfadresBuitenland
        """

        self._verblijfadres = verblijfadres

    @property
    def datum_van(self) -> AbstractDatum:
        """Gets the datum_van of this VerblijfplaatsBuitenland.


        :return: The datum_van of this VerblijfplaatsBuitenland.
        :rtype: AbstractDatum
        """
        return self._datum_van

    @datum_van.setter
    def datum_van(self, datum_van: AbstractDatum):
        """Sets the datum_van of this VerblijfplaatsBuitenland.


        :param datum_van: The datum_van of this VerblijfplaatsBuitenland.
        :type datum_van: AbstractDatum
        """

        self._datum_van = datum_van

    @property
    def datum_ingang_geldigheid(self) -> VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid:
        """Gets the datum_ingang_geldigheid of this VerblijfplaatsBuitenland.


        :return: The datum_ingang_geldigheid of this VerblijfplaatsBuitenland.
        :rtype: VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid
        """
        return self._datum_ingang_geldigheid

    @datum_ingang_geldigheid.setter
    def datum_ingang_geldigheid(self, datum_ingang_geldigheid: VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid):
        """Sets the datum_ingang_geldigheid of this VerblijfplaatsBuitenland.


        :param datum_ingang_geldigheid: The datum_ingang_geldigheid of this VerblijfplaatsBuitenland.
        :type datum_ingang_geldigheid: VerblijfplaatsBuitenlandAllOfDatumIngangGeldigheid
        """

        self._datum_ingang_geldigheid = datum_ingang_geldigheid

    @property
    def in_onderzoek(self) -> VerblijfplaatsBuitenlandInOnderzoek:
        """Gets the in_onderzoek of this VerblijfplaatsBuitenland.


        :return: The in_onderzoek of this VerblijfplaatsBuitenland.
        :rtype: VerblijfplaatsBuitenlandInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: VerblijfplaatsBuitenlandInOnderzoek):
        """Sets the in_onderzoek of this VerblijfplaatsBuitenland.


        :param in_onderzoek: The in_onderzoek of this VerblijfplaatsBuitenland.
        :type in_onderzoek: VerblijfplaatsBuitenlandInOnderzoek
        """

        self._in_onderzoek = in_onderzoek
