from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class VerblijfadresLocatieInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, locatiebeschrijving=None):  # noqa: E501
        """VerblijfadresLocatieInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this VerblijfadresLocatieInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param locatiebeschrijving: The locatiebeschrijving of this VerblijfadresLocatieInOnderzoek.  # noqa: E501
        :type locatiebeschrijving: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'locatiebeschrijving': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'locatiebeschrijving': 'locatiebeschrijving'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._locatiebeschrijving = locatiebeschrijving

    @classmethod
    def from_dict(cls, dikt) -> 'VerblijfadresLocatieInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerblijfadresLocatieInOnderzoek of this VerblijfadresLocatieInOnderzoek.  # noqa: E501
        :rtype: VerblijfadresLocatieInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this VerblijfadresLocatieInOnderzoek.


        :return: The datum_ingang_onderzoek of this VerblijfadresLocatieInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this VerblijfadresLocatieInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this VerblijfadresLocatieInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def locatiebeschrijving(self) -> bool:
        """Gets the locatiebeschrijving of this VerblijfadresLocatieInOnderzoek.


        :return: The locatiebeschrijving of this VerblijfadresLocatieInOnderzoek.
        :rtype: bool
        """
        return self._locatiebeschrijving

    @locatiebeschrijving.setter
    def locatiebeschrijving(self, locatiebeschrijving: bool):
        """Sets the locatiebeschrijving of this VerblijfadresLocatieInOnderzoek.


        :param locatiebeschrijving: The locatiebeschrijving of this VerblijfadresLocatieInOnderzoek.
        :type locatiebeschrijving: bool
        """

        self._locatiebeschrijving = locatiebeschrijving
