from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501

class VerblijfplaatsOnbekendInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, type=None, datum_van=None, datum_ingang_geldigheid=None):  # noqa: E501
        """VerblijfplaatsOnbekendInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this VerblijfplaatsOnbekendInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param type: The type of this VerblijfplaatsOnbekendInOnderzoek.  # noqa: E501
        :type type: bool
        :param datum_van: The datum_van of this VerblijfplaatsOnbekendInOnderzoek.  # noqa: E501
        :type datum_van: bool
        :param datum_ingang_geldigheid: The datum_ingang_geldigheid of this VerblijfplaatsOnbekendInOnderzoek.  # noqa: E501
        :type datum_ingang_geldigheid: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'type': bool,
            'datum_van': bool,
            'datum_ingang_geldigheid': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'type': 'type',
            'datum_van': 'datumVan',
            'datum_ingang_geldigheid': 'datumIngangGeldigheid'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._type = type
        self._datum_van = datum_van
        self._datum_ingang_geldigheid = datum_ingang_geldigheid

    @classmethod
    def from_dict(cls, dikt) -> 'VerblijfplaatsOnbekendInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerblijfplaatsOnbekendInOnderzoek of this VerblijfplaatsOnbekendInOnderzoek.  # noqa: E501
        :rtype: VerblijfplaatsOnbekendInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this VerblijfplaatsOnbekendInOnderzoek.


        :return: The datum_ingang_onderzoek of this VerblijfplaatsOnbekendInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this VerblijfplaatsOnbekendInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this VerblijfplaatsOnbekendInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def type(self) -> bool:
        """Gets the type of this VerblijfplaatsOnbekendInOnderzoek.


        :return: The type of this VerblijfplaatsOnbekendInOnderzoek.
        :rtype: bool
        """
        return self._type

    @type.setter
    def type(self, type: bool):
        """Sets the type of this VerblijfplaatsOnbekendInOnderzoek.


        :param type: The type of this VerblijfplaatsOnbekendInOnderzoek.
        :type type: bool
        """

        self._type = type

    @property
    def datum_van(self) -> bool:
        """Gets the datum_van of this VerblijfplaatsOnbekendInOnderzoek.


        :return: The datum_van of this VerblijfplaatsOnbekendInOnderzoek.
        :rtype: bool
        """
        return self._datum_van

    @datum_van.setter
    def datum_van(self, datum_van: bool):
        """Sets the datum_van of this VerblijfplaatsOnbekendInOnderzoek.


        :param datum_van: The datum_van of this VerblijfplaatsOnbekendInOnderzoek.
        :type datum_van: bool
        """

        self._datum_van = datum_van

    @property
    def datum_ingang_geldigheid(self) -> bool:
        """Gets the datum_ingang_geldigheid of this VerblijfplaatsOnbekendInOnderzoek.


        :return: The datum_ingang_geldigheid of this VerblijfplaatsOnbekendInOnderzoek.
        :rtype: bool
        """
        return self._datum_ingang_geldigheid

    @datum_ingang_geldigheid.setter
    def datum_ingang_geldigheid(self, datum_ingang_geldigheid: bool):
        """Sets the datum_ingang_geldigheid of this VerblijfplaatsOnbekendInOnderzoek.


        :param datum_ingang_geldigheid: The datum_ingang_geldigheid of this VerblijfplaatsOnbekendInOnderzoek.
        :type datum_ingang_geldigheid: bool
        """

        self._datum_ingang_geldigheid = datum_ingang_geldigheid
