from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_datum import AbstractDatum
import re
from openapi_server import util

from openapi_server.models.abstract_datum import AbstractDatum  # noqa: E501
import re  # noqa: E501

class Verificatie(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum=None, omschrijving=None):  # noqa: E501
        """Verificatie - a model defined in OpenAPI

        :param datum: The datum of this Verificatie.  # noqa: E501
        :type datum: AbstractDatum
        :param omschrijving: The omschrijving of this Verificatie.  # noqa: E501
        :type omschrijving: str
        """
        self.openapi_types = {
            'datum': AbstractDatum,
            'omschrijving': str
        }

        self.attribute_map = {
            'datum': 'datum',
            'omschrijving': 'omschrijving'
        }

        self._datum = datum
        self._omschrijving = omschrijving

    @classmethod
    def from_dict(cls, dikt) -> 'Verificatie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Verificatie of this Verificatie.  # noqa: E501
        :rtype: Verificatie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum(self) -> AbstractDatum:
        """Gets the datum of this Verificatie.


        :return: The datum of this Verificatie.
        :rtype: AbstractDatum
        """
        return self._datum

    @datum.setter
    def datum(self, datum: AbstractDatum):
        """Sets the datum of this Verificatie.


        :param datum: The datum of this Verificatie.
        :type datum: AbstractDatum
        """

        self._datum = datum

    @property
    def omschrijving(self) -> str:
        """Gets the omschrijving of this Verificatie.

        Omschrijving van de verificatie van de rni-gegevens   # noqa: E501

        :return: The omschrijving of this Verificatie.
        :rtype: str
        """
        return self._omschrijving

    @omschrijving.setter
    def omschrijving(self, omschrijving: str):
        """Sets the omschrijving of this Verificatie.

        Omschrijving van de verificatie van de rni-gegevens   # noqa: E501

        :param omschrijving: The omschrijving of this Verificatie.
        :type omschrijving: str
        """
        if omschrijving is not None and not re.search(r'^[a-zA-Z0-9À-ž \.\-\']{1,50}$', omschrijving):  # noqa: E501
            raise ValueError(r"Invalid value for `omschrijving`, must be a follow pattern or equal to `/^[a-zA-Z0-9À-ž \.\-\']{1,50}$/`")  # noqa: E501

        self._omschrijving = omschrijving
