from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.gezag_persoon_beperkt import GezagPersoonBeperkt
from openapi_server.models.personen_query_response import PersonenQueryResponse
from openapi_server import util

from openapi_server.models.gezag_persoon_beperkt import GezagPersoonBeperkt  # noqa: E501
from openapi_server.models.personen_query_response import PersonenQueryResponse  # noqa: E501

class ZoekMetAdresseerbaarObjectIdentificatieResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, personen=None):  # noqa: E501
        """ZoekMetAdresseerbaarObjectIdentificatieResponse - a model defined in OpenAPI

        :param type: The type of this ZoekMetAdresseerbaarObjectIdentificatieResponse.  # noqa: E501
        :type type: str
        :param personen: The personen of this ZoekMetAdresseerbaarObjectIdentificatieResponse.  # noqa: E501
        :type personen: List[GezagPersoonBeperkt]
        """
        self.openapi_types = {
            'type': str,
            'personen': List[GezagPersoonBeperkt]
        }

        self.attribute_map = {
            'type': 'type',
            'personen': 'personen'
        }

        self._type = type
        self._personen = personen

    @classmethod
    def from_dict(cls, dikt) -> 'ZoekMetAdresseerbaarObjectIdentificatieResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ZoekMetAdresseerbaarObjectIdentificatieResponse of this ZoekMetAdresseerbaarObjectIdentificatieResponse.  # noqa: E501
        :rtype: ZoekMetAdresseerbaarObjectIdentificatieResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ZoekMetAdresseerbaarObjectIdentificatieResponse.


        :return: The type of this ZoekMetAdresseerbaarObjectIdentificatieResponse.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ZoekMetAdresseerbaarObjectIdentificatieResponse.


        :param type: The type of this ZoekMetAdresseerbaarObjectIdentificatieResponse.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def personen(self) -> List[GezagPersoonBeperkt]:
        """Gets the personen of this ZoekMetAdresseerbaarObjectIdentificatieResponse.

        * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.   # noqa: E501

        :return: The personen of this ZoekMetAdresseerbaarObjectIdentificatieResponse.
        :rtype: List[GezagPersoonBeperkt]
        """
        return self._personen

    @personen.setter
    def personen(self, personen: List[GezagPersoonBeperkt]):
        """Sets the personen of this ZoekMetAdresseerbaarObjectIdentificatieResponse.

        * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.   # noqa: E501

        :param personen: The personen of this ZoekMetAdresseerbaarObjectIdentificatieResponse.
        :type personen: List[GezagPersoonBeperkt]
        """

        self._personen = personen
